### ISSUE TITLE
console.log viewer

### ISSUE THREAD

**Issue by fmenezes** [driftyco/ionic-view-issues#120]
My app doesn't show up and I'm lost, is there any way to see the console.logs to try some debugging?

**Comment by simplesmiler** [comment]
@fmenezes  you could try [weinre](http://people.apache.org/~pmuellr/weinre/).

It provides you with at least:
- interactive console with log
- elements tree (with limited support for editing html and styles)

You could also try the good old `alert`. Not perfect but something.

**Comment by tlancina** [comment]
Yes this is something we would like to address, as many users feel stranded when they can't figure out what went wrong.  Unfortunately you can't debug using any sort of inspector because it is a production signed app, but as a workaround you could append console.logs as elements with text or use alerts as @simplesmiler mentioned.
