### ISSUE TITLE
Confirmation pop up not Appearing

### ISSUE THREAD

**Issue by x-amb** [driftyco/ionic-view-issues#132]
Dear All,
Im trying to show a popup on back navigation before i exit the application. But the pop up seems not to appear. Please help me to solve this. 
This is the code i have written

.run(function($ionicPlatform, $ionicPopup) {
	$ionicPlatform.registerBackButtonAction(function (event) {
      if($state.current.name == "login"){

        var confo = $ionicPopup.confirm({
               title: 'Log Out',
               template: 'Are you sure you want to Log Out?'
             });
             confo.then(function(res) {
                if(res) {
                    navigator.app.exitApp();
                } else {
                  console.log('You are not sure');
                }
             });
      }
      else {
        navigator.app.backHistory();
      }
    }, 100);
})

**Comment by Ionitron** [comment]
Greetings @x-amb!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
