### ISSUE TITLE
Fork Ionic View to add Plugins?

### ISSUE THREAD

**Issue by kevbaker** [driftyco/ionic-view-issues#135]
I know currently Ionic View is private. I would like to fork the project to add the plugins we need. 

Or have a way to have updates made to the production Ionic View that include our required plugins.

### Why?

We want to avoid UDID process for Apple, something Ionic View is great about. Apple takes too long to send out invites for our beta workflow under the TestFlight system.

Thoughts?

**Comment by Ionitron** [comment]
Greetings @kevbaker!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
