### ISSUE TITLE
HTTPS and unverified CA

### ISSUE THREAD

**Issue by podger** [driftyco/ionic-view-issues#136]
Hi,
i'm having some issues in Ionic View trying to consume a web service via https that uses a certicate not signed by any global CA. By installing the app directly on the the phone however the requests work just fine. 
How can I solve this problem on Ionic View, do you have any suggestions?

**Comment by Ionitron** [comment]
Greetings @podger!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
