### ISSUE TITLE
InAppBrowser only offers Cordova API access on Ionic View

### ISSUE THREAD

**Issue by msfilho** [driftyco/ionic-view-issues#180]
Hi,

I know this is not an specific problem on "Ionic View", but since this is the only place it works, maybe you can explain why and help me.

Looking the Angular code of your "Ionic View" app (extracted from my device), it's clear that you loads the User App using InAppBrowser (injecting cordova.js). I don't know how, but the Cordova API is accessible inside InAppBrowser (on Ionic View), which goes against the official InAppBrowser documentation: "...behaves like a standard web browser, and can't access Cordova APIs...".
The official behaviour is exactly what happens when i build my own app with the same plugin enabled, the page opens but can't access Cordova API commands.

Is this an specific mod for "Ionic View" (changes in Native code) or should i enable some preference in config.xml to allow the same behaviour?

Any tips?

**Comment by tlancina** [comment]
Hey @msfilho, we use our own custom version of InAppBrowser with modifications specific to View that allows access to the Cordova APIs.

**Comment by msfilho** [comment]
Hi @tlancina, thank you for answer.

Is it possible to release this modification for us?

Thanks

**Comment by tlancina** [comment]
We've discussed open sourcing View, but it would need some clean up first. At the moment it's not a high priority, but definitely something that might happen down the road.

For the general gist of what's going on, you could take a look at https://github.com/kunder-lab/cl.kunder.webview, which looks like it does the same thing.

Just remember, if you're going to be loading 3rd party code in a webview with Cordova API access, you want to be careful since allowing arbitrary websites access to native APIs could be a security issue depending on what you're doing.

**Comment by msfilho** [comment]
Thank you @tlancina.
