### ISSUE TITLE
Sign Up

### ISSUE THREAD

**Issue by werne2j** [driftyco/ionic-view-issues#34]
When i try to sign up, the app does nothing. When i click the sign up button, it goes into a loading screen but just returns back to the sign up form.

**Comment by tlancina** [comment]
Hey there were some changes to server side error responses while the app was in review, so error parsing is broken for signups currently.

It most likely means:
- you already signed up with that email
- there are invalid characters in your username (spaces, @, etc.)
- the passwords don't match

This will be fixed in the next release
