### ISSUE TITLE
Cordova Splashscreen Plugin

### ISSUE THREAD

**Issue by paulsutherland** [driftyco/ionic-view-issues#39]
Hi Guys,

Firstly, what great work you have done here - this is an amazing tool - well done.

I just wanted to report that the cordova splash screen plugin does not appear to work.  It displays a white screen then jumps straight into the app.  Splash screens working elsewhere, on the device, emulator etc.

I used the resource option in the Ionic CLI for iOS to generate the splash screen assets and I am using the iOS Ionic view app.

Thanks,

Paul

**Comment by tlancina** [comment]
If I remember right splash screen is explicitly disabled because with the
current implementation of View it would just show View's splash screen.
All View does is load the www content of your app, not any of the icon or
splash resources.

Although maybe that's fine if you just need to mock the behavior. Any
thoughts?

**Comment by paulsutherland** [comment]
Ok I understand.  The plugins list on http://docs.ionic.io/tools/viewapp/ suggested that the splashscreen was enabled, my expectation was to see it when the app loaded in Ionic view.  However, I do not require it as it is fine for demoing a mock up of the app. 

I just thought I would raise an issue in case it was expected to show a splash for each app.

Thanks,

Paul

**Comment by tlancina** [comment]
Ah that should not be in the list of available plugins, good catch! I've removed it.
