### ISSUE TITLE
Clarification needed: Ionic View App

### ISSUE THREAD

**Issue by pearlsj** [driftyco/ionic-view-issues#83]
As it's not documented, where exactly is the code uploaded to when you run the `ionic upload` command?

**Comment by tlancina** [comment]
The zipped www folder is stored in a private Amazon s3 bucket with a random hash name that can only be downloaded with a signed, temporary link that expires after a few minutes.

I'm going to close this just because it's not an issue with View per se, but feel free to comment if you need any clarification.

**Comment by pearlsj** [comment]
@tlancina That is more than satisfactory. Thank you!

**Comment by VSVS** [comment]
How can i download this zipped file? Where do i retrieve this link?

**Comment by VSVS** [comment]
Doesn't seem possible at the moment. Was just wondering because i moved computers. 
source: http://stackoverflow.com/questions/32043165/how-to-download-the-source-code-from-ionic-view
