### ISSUE TITLE
Is the statusbar plugin being used automatically?

### ISSUE THREAD

**Issue by cfjedimaster** [driftyco/ionic-view-issues#9]
I noticed that when I viewed the default app in Ionic View, the status bar fix was not being used. The app was still usable, but it definitely 'bled' a bit into the status bar. When I run it locally on the iOS emulator it is fixed there.

A minor nit, but I'd expect what I see in the emulator to match Ionic View. 

(I can send a screen shot of both if you want.)

**Comment by tlancina** [comment]
The fix is sitting in the iOS App Store Review for the next release, should be out within a week (assuming the review team gets to it in a timely fashion).  

Ionic needs `platform-ios` and `platform-cordova` classes on the body tag to adjust for the statusbar.

Leaving this open until it's resolved.

**Comment by tlancina** [comment]
Should be fixed with latest update, feel free to re-open if you're still having issues.
