### ISSUE TITLE
ionic view with cordova whitelist plugin

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic-view-issues#94]
My app was working fine on ionic view  & deployed on android 4.4 until I upgraded to the latest version of cordova/ionic. At that point in time all http requests were returning 404s and I figured out that I needed the whitelist plugin for Cordova 5.0.

Now my app works fine when deployed on android 4.4 but fails on the ionic view app. I suspect I am getting 404s again, but I can't debug the view app. Is there a better way to use the view app with cordova 5.0 & http requests? What should I do? 

OS: Windows 8.1
Node Version: v0.12.2
Cordova CLI: 5.0.0
Ionic Version: 1.0.0-rc.2
Ionic CLI Version: 1.3.22

**Comment by tlancina** [comment]
Hmm I'm not quite sure why it would be failing, since View uses its own cordova.js and cordova-android I believe, which haven't been updated to 3.9 (or whatever cordova 5.0 uses) and 4.0 respectively yet.

When you say it fails on View, what do you mean? Just blank screen like nothing loads, or something else?

**Comment by djangojack** [comment]
Thanks for the reply. I dug in further and discovered that the view app was persisting data instead of deleting it when I would hit clear app data / download files. This solved the problem!

**Comment by tlancina** [comment]
Ah another victim of #10!  I'll be looking it for Android later today, since it should be fixed on iOS. 

Closing as a dup for now.
